### ISSUE TITLE
[PATCH][v2] fstests: btrfs/218 add a test for btrfs seed device stats

### ISSUE THREAD

**Issue by josefbacik** [btrfs/fstests#2]
Link to patches

https://lore.kernel.org/linux-btrfs/979d061f9957629bc5b89a9d74ae5673d75eb68d.1597948086.git.josef@toxicpanda.com/

b4 am 979d061f9957629bc5b89a9d74ae5673d75eb68d.1597948086.git.josef@toxicpanda.com

**Comment by morbidrsa** [comment]
Already in upstream fstests, can we close this one?
