### ISSUE TITLE
btrfs/125 ERROR: error during balancing: -EIO

### ISSUE THREAD

**Issue by kdave** [btrfs/fstests#20]
```
btrfs/125               [23:16:17] [23:17:04]47s - output mismatch (see /root/xfstests-git/results//btrfs/125.out.bad)
    --- tests/btrfs/125.out     2016-09-22 14:38:07.708090747 +0200
    +++ /root/xfstests-git/results//btrfs/125.out.bad   2020-09-10 23:17:04.113205127 +0200
    @@ -3,5 +3,15 @@
     Write data with degraded mount

     Mount normal and balance
    +ERROR: error during balancing '/mnt/fstests/scratch_mnt': Input/output error
    +There may be more info in syslog - try dmesg | tail
    +md5sum: /mnt/fstests/scratch_mnt/tf2: Input/output error

    ...
```

**Comment by fdmanana** [comment]
The test fails very sporadically due to the RAID5/6 corruption I reported months ago on the mailing list:

https://lore.kernel.org/linux-btrfs/CAL3q7H4oa70DUhOFE7kot62KjxcbvvZKxu62VfLpAcmgsinBFw@mail.gmail.com/

**Comment by morbidrsa** [comment]
> The test fails very sporadically due to the RAID5/6 corruption I reported months ago on the mailing list:
> 
> https://lore.kernel.org/linux-btrfs/CAL3q7H4oa70DUhOFE7kot62KjxcbvvZKxu62VfLpAcmgsinBFw@mail.gmail.com/

In my setup (6 3G zram devices, one for TEST_DEV the others as SCRATCH_DEV_POOL) this tests fails deterministically, so I can try debug/fix patches easily.

**Comment by fdmanana** [comment]
> > The test fails very sporadically due to the RAID5/6 corruption I reported months ago on the mailing list:
> > https://lore.kernel.org/linux-btrfs/CAL3q7H4oa70DUhOFE7kot62KjxcbvvZKxu62VfLpAcmgsinBFw@mail.gmail.com/
> 
> In my setup (6 3G zram devices, one for TEST_DEV the others as SCRATCH_DEV_POOL) this tests fails deterministically, so I can try debug/fix patches easily.

The reason the problem was not yet fixed is because I can't find a way to fix it without making performance suck, not because of difficulty in testing patches.

I believe we had a brief chat about this sometime ago on slack - partial stripe writes are very frequent, and making every partial stripe write also read, validate, and repair if validation fails, every allocated extent in the stripe is expensive, extra IO - direct impact on transaction commits and fsync for example. And partial stripe writes are very common.

It's fundamentally a design issue of btrfs' raid5/6 implementation.

**Comment by morbidrsa** [comment]
> The reason the problem was not yet fixed is because I can't find a way to fix it without making performance suck, not because of difficulty in testing patches.
> 
> I believe we had a brief chat about this sometime ago on slack - partial stripe writes are very frequent, and making every partial stripe write also read, validate, and repair if validation fails, every allocated extent in the stripe is expensive, extra IO - direct impact on transaction commits and fsync for example. And partial stripe writes are very common.
> 
> It's fundamentally a design issue of btrfs' raid5/6 implementation.

Right I now remember. @fdmanana @kdave are you ok with removing the test from the auto group then until a replacement for RAID5/6 is in sight?

**Comment by fdmanana** [comment]
> > The reason the problem was not yet fixed is because I can't find a way to fix it without making performance suck, not because of difficulty in testing patches.
> > I believe we had a brief chat about this sometime ago on slack - partial stripe writes are very frequent, and making every partial stripe write also read, validate, and repair if validation fails, every allocated extent in the stripe is expensive, extra IO - direct impact on transaction commits and fsync for example. And partial stripe writes are very common.
> > It's fundamentally a design issue of btrfs' raid5/6 implementation.
> 
> Right I now remember. @fdmanana @kdave are you ok with removing the test from the auto group then until a replacement for RAID5/6 is in sight?

Fine by me.

**Comment by kdave** [comment]
Agreed.

**Comment by kdave** [comment]
https://lore.kernel.org/linux-btrfs/20200923164426.19534-1-johannes.thumshirn@wdc.com/

**Comment by kdave** [comment]
6e723496c1bc2812dbe920578d4c291bbf33d6a7 merged
