### ISSUE TITLE
btrfs/163 is failing

### ISSUE THREAD

**Issue by lorddoskias** [btrfs/fstests#34]
That test fails following "btrfs: fix replace of seed device" since that commit now disallows  seed device replace. fstests patch submitted at https://lore.kernel.org/linux-btrfs/20200924121910.22477-1-nborisov@suse.com/T/#u

**Comment by lorddoskias** [comment]
Turns out there is already a patch submitted for this test here: https://patchwork.kernel.org/patch/11758651/

**Comment by kdave** [comment]
Fixed in fstests by 577e8c932989511973bcfdf48b22c5cf540c93f9
