### ISSUE TITLE
btrfs/064 seems to be doing replace incorrectly?

### ISSUE THREAD

**Issue by josefbacik** [btrfs/fstests#37]
my btrfs/064.full shows a lot of this

```
Test -m raid1 -d raid1
Run fsstress  -p 20 -n 100 -d /mnt/scratch/stressdir
Start balance worker: 2634411
Start replace worker: 2634412
Wait for fsstress to exit and kill all background workers
dev_pool=/dev/mapper/vg0-lv8 /dev/mapper/vg0-lv7 /dev/mapper/vg0-lv6 /dev/mapper/vg0-lv5 /dev/mapper/vg0-lv4 /dev/mapper/vg0-lv3 /dev/mapper/vg0-lv2
free_dev=/dev/mapper/vg0-lv1, src_dev=/dev/mapper/vg0-lv8
Replacing /dev/mapper/vg0-lv8 with /dev/mapper/vg0-lv1
ERROR: ioctl(DEV_REPLACE_START) '/mnt/scratch': add/delete/balance/replace/resize operation in progress
Replacing /dev/mapper/vg0-lv7 with /dev/mapper/vg0-lv8
ERROR: /dev/mapper/vg0-lv8 is mounted
Replacing /dev/mapper/vg0-lv7 with /dev/mapper/vg0-lv8
ERROR: /dev/mapper/vg0-lv8 is mounted
Replacing /dev/mapper/vg0-lv7 with /dev/mapper/vg0-lv8
ERROR: /dev/mapper/vg0-lv8 is mounted
Replacing /dev/mapper/vg0-lv7 with /dev/mapper/vg0-lv8
ERROR: /dev/mapper/vg0-lv8 is mounted
```

We run replace in a loop as a stress, but it appears to not be doing anything?  I noticed this while looking into a hang with btrfs/064.  The test should probably be fixed to actually do the replace properly, or remove the replace if it's inappropriate.

**Comment by josefbacik** [comment]
@asj can you look into this?  It was written by Eryu like 6 years ago, maybe it doesn't make sense to do the replace with balance?

**Comment by asj** [comment]
Oh  even though btrfs/064 runs fine on my setup, the btrfs replace was never started successfully as per $seqres.full output
 ERROR: ioctl(DEV_REPLACE_START) '/mnt/scratch': add/delete/balance/replace/resize operation in progress
Balance and replace aren't concurrent, so this test case does not make sense. I am thinking to delete this test case.

**Comment by kdave** [comment]
The test seems to be working as intended, the balance and replace exclusion is known. I'd keep it there as a stress test, I haven't seen any test failures.
