### ISSUE TITLE
btrfs/179 hangs if we get a transaction abort during the test

### ISSUE THREAD

**Issue by josefbacik** [btrfs/fstests#40]
I had a transient ENOMEM while running btrfs/179 on my vm, and it hung because the test does

```
$BTRFS_UTIL_PROG subvolume sync $SCRATCH_MNT
```

Which waits for any deleted subvolumes to finish deleting.  The problem is if we get an aborted transaction before (or even during this) we'll just spin forever because the subvolumes are never going to be deleted.  We can fix this in the test a little bit by checking if we can write to the fs before doing `subvolume sync` but we should probably fix `subvolume sync` to recognize that the fs is read only and thus won't make progress.

**Comment by kdave** [comment]
As subvol sync does polling it can do the read-only check too, but what is the cannonical way to do that?

**Comment by josefbacik** [comment]
I think statfs and check ->f_flags for ST_RDONLY is the best way?

**Comment by kdave** [comment]
Fix tracked in https://github.com/kdave/btrfs-progs/issues/535 .
