### ISSUE TITLE
generic/102 fails sporadically.

### ISSUE THREAD

**Issue by lorddoskias** [btrfs/fstests#52]
generic/102 can fail sporadically with an ENOSPC error. Following a detailed investigation this seems to be caused by a race condition in the way ordered extents are completed. Essentially the process of completing an OE consists of 2 stages :  

 1. First one is removing the OE from the root's list of ordered extents, this happens in btrfs_removed_ordered_extent. This means any waiters (like btrfs_start_ordered_extent will return at this point). 
 
 2. Subsequently btrfs_put_ordered_extent is called which actually calls iput for the inode that this OE belongs to. 
 
This sequence of events is problematic in the context of waiting for ordered extents to be flushed, because the flushing machinery will think that all extents have been disposed of, because they are no longer on the root's list, yet those same extent might not have been really disposed of, because their respective iput not being run. 
This will confuse the data flushing machinery to go and retry a reservation following calling shrink_delalloc which would just see there is space used and nothing can be freed which eventually results in premature ENOSPC.

**Comment by kdave** [comment]
A relatively recent failure found in my logs on 5.19.0-rc1:

```
generic/102             [13:37:54][ 6080.556294] run fstests generic/102 at 2022-06-08 13:37:54
[ 6080.901916] BTRFS info (device vda): flagging fs with big metadata feature
[ 6080.901924] BTRFS info (device vda): using free space tree
[ 6080.901927] BTRFS info (device vda): has skinny extents
[ 6081.022228] BTRFS: device fsid b72ef132-fb2e-44fc-8f09-498076bc9fca devid 1 transid 6 /dev/vdb scanned by mkfs.btrfs (19246)
[ 6081.034324] BTRFS info (device vdb): flagging fs with big metadata feature
[ 6081.034329] BTRFS info (device vdb): using free space tree
[ 6081.034330] BTRFS info (device vdb): has skinny extents
[ 6081.036822] BTRFS info (device vdb): checking UUID tree
[ 6088.292719] BTRFS info (device vdb): flagging fs with big metadata feature
[ 6088.292723] BTRFS info (device vdb): using free space tree
[ 6088.292724] BTRFS info (device vdb): has skinny extents
 [13:38:02]8s - output mismatch (see /tmp/fstests/results//generic/102.out.bad)
    --- tests/generic/102.out   2018-10-08 09:51:53.890556726 +0000
    +++ /tmp/fstests/results//generic/102.out.bad       2022-06-08 13:38:02.524000000 +0000
    @@ -5,8 +5,7 @@
     XXX Bytes, X ops; XX:XX:XX.X (XXX YYY/sec and XXX ops/sec)
     wrote 838860800/838860800 bytes at offset 0
     XXX Bytes, X ops; XX:XX:XX.X (XXX YYY/sec and XXX ops/sec)
    -wrote 838860800/838860800 bytes at offset 0
    -XXX Bytes, X ops; XX:XX:XX.X (XXX YYY/sec and XXX ops/sec)
    +pwrite: No space left on device
     wrote 838860800/838860800 bytes at offset 0
     XXX Bytes, X ops; XX:XX:XX.X (XXX YYY/sec and XXX ops/sec)
     wrote 838860800/838860800 bytes at offset 0
    ...
    (Run 'diff -u /tmp/fstests/tests/generic/102.out /tmp/fstests/results//generic/102.out.bad'  to see the entire diff)
```
